name: Install Signadot
on: [push]

jobs:
  kind:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind-node:
          - kindest/node:v1.20.2
          - kindest/node:v1.19.7
          - kindest/node:v1.18.15
          - kindest/node:v1.17.17
          - kindest/node:v1.16.15
        signadot-version:
          - v0.5.2
    steps:
      - uses: actions/checkout@master

      - uses: asdf-vm/actions/install@v1

      # - uses: engineerd/setup-kind@v0.5.0
      #   with:
      #     version: v0.10.0
      #     image: ${{ matrix.kind-node }}
      - name: Install signadot
        run: |
          curl -o signadot.zip https://signadot-helm.s3-us-west-2.amazonaws.com/release/${{ matrix.signadot-version }}/signadot.zip
          unzip signadot.zip
          cd signadot

          ./util/gen-certs.sh
          dasel put string -f values.yaml '.sidecar-injector.caBundle' $(cat util/secret.yaml | dasel -p yaml select -s '.data.cert\.pem')

          kubectl create ns signadot
          helm install --wait --namespace=signadot --set sidecar-injector.enabled=true signadot ./

          cd ../
          kubectl apply -f echoserver.yaml

          sleep 10
          kubectl get pods -A
