name: Install Signadot
on: [push]

jobs:
  kind:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind-node:
          - kindest/node:v1.20.2
          - kindest/node:v1.19.7
          - kindest/node:v1.18.15
          - kindest/node:v1.17.17
          - kindest/node:v1.16.15
        signadot-version:
          - v0.5.2
    steps:
      - uses: actions/checkout@master

      - uses: asdf-vm/actions/install@v1

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.10.0
          image: ${{ matrix.kind-node }}

      - name: Install signadot
        run: |
          curl -o signadot.zip https://signadot-helm.s3-us-west-2.amazonaws.com/release/${{ matrix.signadot-version }}/signadot.zip
          unzip signadot.zip
          cd signadot

          ./util/gen-certs.sh
          dasel put string -f values.yaml '.sidecar-injector.caBundle' $(cat util/secret.yaml | dasel -p yaml select -s '.data.cert\.pem')

          kubectl create ns signadot
          kubectl apply -f ./util/secret.yaml
          helm install --namespace=signadot --set sidecar-injector.enabled=true signadot ./

          sleep 10

          kubectl -n signadot wait --timeout=30s --for=condition=ready pod -l sd-component=proxy
          kubectl -n signadot wait --timeout=30s --for=condition=ready pod -l app=sd-sidecar-injector

          cd ../
          kubectl apply -f echoserver.yaml
          kubectl wait --timeout=30s --for=condition=ready pod -l app=nginx

          kubectl -n signadot logs $(kubectl -n signadot get pod -l app=sd-sidecar-injector -o name) | tee injector-logs.txt
          if grep -q "TLS handshake error" injector-logs.txt; then
            echo "Injection failed"
            exit -1;
          fi
